// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChAkzcCW7pTSu76YYeBjNnr3Hqpo7S6LU',
    appId: '1:942660829556:web:0a3e605107ba13de0c6c21',
    messagingSenderId: '942660829556',
    projectId: 'auth-685cc',
    authDomain: 'auth-685cc.firebaseapp.com',
    storageBucket: 'auth-685cc.firebasestorage.app',
    measurementId: 'G-R2E3RYVZK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtwy5Sq3JcSBbmvxh9S2bhMr99CexYbJE',
    appId: '1:942660829556:android:75f51e7351c6f17f0c6c21',
    messagingSenderId: '942660829556',
    projectId: 'auth-685cc',
    storageBucket: 'auth-685cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBf4nytliaeurgyFrJT5PwBwGGMZ3MdMg',
    appId: '1:942660829556:ios:02353b93323788d90c6c21',
    messagingSenderId: '942660829556',
    projectId: 'auth-685cc',
    storageBucket: 'auth-685cc.firebasestorage.app',
    iosBundleId: 'com.example.otpAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBf4nytliaeurgyFrJT5PwBwGGMZ3MdMg',
    appId: '1:942660829556:ios:02353b93323788d90c6c21',
    messagingSenderId: '942660829556',
    projectId: 'auth-685cc',
    storageBucket: 'auth-685cc.firebasestorage.app',
    iosBundleId: 'com.example.otpAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChAkzcCW7pTSu76YYeBjNnr3Hqpo7S6LU',
    appId: '1:942660829556:web:5948ceb492edfc9e0c6c21',
    messagingSenderId: '942660829556',
    projectId: 'auth-685cc',
    authDomain: 'auth-685cc.firebaseapp.com',
    storageBucket: 'auth-685cc.firebasestorage.app',
    measurementId: 'G-N1C4P2K77S',
  );
}
